//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetBuddy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenses
    {
        public int expenseId { get; set; }
        public string billName { get; set; }
        public decimal billPrice { get; set; }
        public System.DateTime purchaseDate { get; set; }
        public Nullable<int> Id { get; set; }
        public bool recurringExpense { get; set; }
        public Nullable<decimal> savingPercentage { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
