//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetBuddy
{
    using System;
    using System.Collections.Generic;
    
    public partial class WishLists
    {
        public int wishListId { get; set; }
        public string wishListName { get; set; }
        public decimal wishListPrice { get; set; }
        public Nullable<int> Id { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
